import { forwardRef } from "react";

const DECISION_META = {
  APPROVED: { label: "Approved", className: "approved" },
  CONDITIONAL: { label: "Conditional", className: "conditional" },
  REJECTED: { label: "Rejected", className: "rejected" },
};

const dateFmt = new Intl.DateTimeFormat("en-IN", {
  day: "2-digit",
  month: "long",
  year: "numeric",
});

const currency = new Intl.NumberFormat("en-IN", {
  style: "currency",
  currency: "INR",
  maximumFractionDigits: 0,
});

/**
 * Rendered off-screen (see ResultStamp) and captured to an image for PDF export.
 * Kept as a separate, fixed-width component so the exported document looks
 * consistent regardless of the viewport it was generated from.
 */
const Certificate = forwardRef(function Certificate({ result }, ref) {
  if (!result) return null;
  const meta = DECISION_META[result.decision];

  return (
    <div className="certificate" ref={ref}>
      <div className="certificate-header">
        <div>
          <div className="certificate-eyebrow">Ledger &amp; Co.</div>
          <div className="certificate-title">Certificate of Loan Eligibility Assessment</div>
        </div>
        <div className="certificate-ref">
          REF: LE-{String(result.id).padStart(4, "0")}
          <br />
          {dateFmt.format(result.createdAt)}
        </div>
      </div>

      <div className="certificate-body">
        <div className="certificate-row">
          <span className="certificate-label">Applicant</span>
          <span className="certificate-value">{result.fullName}</span>
        </div>
        <div className="certificate-row">
          <span className="certificate-label">Requested Loan Amount</span>
          <span className="certificate-value">{currency.format(result.requestedLoanAmount)}</span>
        </div>
        <div className="certificate-row">
          <span className="certificate-label">Assessment Score</span>
          <span className="certificate-value">{result.totalScore} / 100</span>
        </div>

        <div className="certificate-stamp-wrap">
          <span className={`certificate-stamp ${meta.className}`}>{meta.label}</span>
        </div>

        <div className="certificate-table">
          <div className="certificate-table-head">
            <span>Factor</span>
            <span>Score</span>
            <span>Assessment</span>
          </div>
          {result.breakdown.map((factor) => (
            <div className="certificate-table-row" key={factor.key}>
              <span className="certificate-factor-label">{factor.label}</span>
              <span className="certificate-factor-score">
                {factor.score} / {factor.maxScore}
              </span>
              <span className="certificate-factor-note">{factor.note}</span>
            </div>
          ))}
        </div>

        <p className="certificate-footnote">
          This certificate is generated by a deterministic rule-based assessment engine for
          demonstration purposes and does not constitute a binding loan offer or a decision by any
          licensed lending institution.
        </p>

        <div className="certificate-signature">
          <div className="certificate-sig-line">
            <span>Authorized &mdash; Ledger &amp; Co. Rule Engine v1.0</span>
          </div>
          <div className="certificate-sig-line">
            <span>Issued {dateFmt.format(new Date())}</span>
          </div>
        </div>
      </div>
    </div>
  );
});

export default Certificate;
