import { useEffect, useState } from "react";
import LoanForm from "./components/LoanForm.jsx";
import ResultStamp from "./components/ResultStamp.jsx";
import HistoryPanel from "./components/HistoryPanel.jsx";
import Toast from "./components/Toast.jsx";
import { computeEligibility } from "./logic/eligibilityEngine.js";

const STORAGE_KEY = "loan-eligibility-history-v1";

function loadHistory() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return parsed.map((entry) => ({ ...entry, createdAt: new Date(entry.createdAt) }));
  } catch {
    return [];
  }
}

export default function App() {
  const [tab, setTab] = useState("apply"); // "apply" | "history"
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [formKey, setFormKey] = useState(0);
  const [toast, setToast] = useState(null);
  const [history, setHistory] = useState(() => loadHistory());

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(history));
  }, [history]);

  useEffect(() => {
    if (!toast) return;
    const t = setTimeout(() => setToast(null), 3200);
    return () => clearTimeout(t);
  }, [toast]);

  function handleSubmit(payload) {
    setError(null);
    setSubmitting(true);
    setResult(null);

    // Brief artificial delay so the "stamping" state and reveal animation
    // actually register instead of the result appearing instantly.
    setTimeout(() => {
      try {
        const { totalScore, decision, breakdown } = computeEligibility(payload);
        const entry = {
          id: history.length > 0 ? Math.max(...history.map((h) => h.id)) + 1 : 1,
          fullName: payload.fullName,
          requestedLoanAmount: payload.requestedLoanAmount,
          totalScore,
          decision,
          breakdown,
          createdAt: new Date(),
        };
        setResult(entry);
        setHistory((prev) => [entry, ...prev]);
        setToast({ message: `${payload.fullName}: ${decision.toLowerCase()} (${totalScore}/100)`, tone: decision });
      } catch {
        setError("Something went wrong evaluating this application.");
      } finally {
        setSubmitting(false);
      }
    }, 550);
  }

  function handleReset() {
    setResult(null);
    setError(null);
    setFormKey((k) => k + 1);
  }

  function handleClearHistory() {
    if (!window.confirm("Clear all applications from the register? This can't be undone.")) return;
    setHistory([]);
    localStorage.removeItem(STORAGE_KEY);
  }

  return (
    <div className="app">
      <header className="letterhead">
        <div>
          <div className="eyebrow">Ledger &amp; Co. &mdash; Est. 2026</div>
          <h1>Loan Eligibility Register</h1>
        </div>
        <div className="ref">
          FORM NO. LE-01
          <br />
          RULE-BASED ASSESSMENT
        </div>
      </header>

      <nav className="tab-nav">
        <button
          className={`tab-btn ${tab === "apply" ? "active" : ""}`}
          onClick={() => setTab("apply")}
        >
          New Application
        </button>
        <button
          className={`tab-btn ${tab === "history" ? "active" : ""}`}
          onClick={() => setTab("history")}
        >
          Register / History
        </button>
      </nav>

      {tab === "apply" ? (
        <div className="ledger-grid">
          <LoanForm key={formKey} onSubmit={handleSubmit} loading={submitting} error={error} />
          <div className="paper result-panel">
            <ResultStamp result={result} loading={submitting} onReset={handleReset} />
          </div>
        </div>
      ) : (
        <HistoryPanel history={history} onClear={handleClearHistory} />
      )}

      <p className="footer-note">
        Decisions are generated by a deterministic rule engine, not a licensed lender. History is
        saved to this browser only (localStorage) &mdash; nothing leaves your machine.
      </p>

      <Toast toast={toast} />
    </div>
  );
}
