import { useState } from "react";
import LoanForm from "./components/LoanForm.jsx";
import ResultStamp from "./components/ResultStamp.jsx";
import HistoryPanel from "./components/HistoryPanel.jsx";
import { computeEligibility } from "./logic/eligibilityEngine.js";

export default function App() {
  const [tab, setTab] = useState("apply"); // "apply" | "history"
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [history, setHistory] = useState([]);

  function handleSubmit(payload) {
    setError(null);
    try {
      const { totalScore, decision, breakdown } = computeEligibility(payload);
      const entry = {
        id: history.length + 1,
        fullName: payload.fullName,
        requestedLoanAmount: payload.requestedLoanAmount,
        totalScore,
        decision,
        breakdown,
        createdAt: new Date(),
      };
      setResult(entry);
      setHistory((prev) => [entry, ...prev]);
    } catch (err) {
      setError("Something went wrong evaluating this application.");
      setResult(null);
    }
  }

  return (
    <div className="app">
      <header className="letterhead">
        <div>
          <div className="eyebrow">Ledger &amp; Co. &mdash; Est. 2026</div>
          <h1>Loan Eligibility Register</h1>
        </div>
        <div className="ref">
          FORM NO. LE-01
          <br />
          RULE-BASED ASSESSMENT
        </div>
      </header>

      <nav className="tab-nav">
        <button
          className={`tab-btn ${tab === "apply" ? "active" : ""}`}
          onClick={() => setTab("apply")}
        >
          New Application
        </button>
        <button
          className={`tab-btn ${tab === "history" ? "active" : ""}`}
          onClick={() => setTab("history")}
        >
          Register / History
        </button>
      </nav>

      {tab === "apply" ? (
        <div className="ledger-grid">
          <LoanForm onSubmit={handleSubmit} loading={false} error={error} />
          <div className="paper result-panel">
            <ResultStamp result={result} />
          </div>
        </div>
      ) : (
        <HistoryPanel history={history} />
      )}

      <p className="footer-note">
        Decisions are generated by a deterministic rule engine, not a licensed lender. Running fully
        client-side right now &mdash; nothing is saved once you refresh the page.
      </p>
    </div>
  );
}
